config/routes.rb
Rails.application.routes.draw do

  root 'user_urls#new'

  resources :user_urls, only: [:index, :show, :create, :new] do
    resources :url_statistics, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_statistic.rb
class UrlStatistic < ApplicationRecord
  belongs_to :user_url
end

app/models/user_url.rb
class UserUrl < ApplicationRecord
  validates :long_url, presence: true, format: URI::regexp(%w[http https])
  validates :short_url, presence: true

  has_many :url_statistics, dependent: :destroy

  scope :all_urls, -> {
    all.order(created_at: :desc)
  }

  def make_short_url
    "http://chitch.at/#{SecureRandom.alphanumeric}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_statistics_controller.rb
class UrlStatisticsController < ApplicationController
  before_action :find_url

  # Show all statistics for a given URL
  def index
    @statistics = @url.url_statistics
  end

  private

  def find_url
    @url = UserUrl.find(params[:user_url_id])
  end
end

app/controllers/user_urls_controller.rb
class UserUrlsController < ApplicationController

  def index
    @urls = UserUrl.all_urls
  end

  def show
    @url = UserUrl.find(params[:id])
    log_ip_address
    redirect_to @url.long_url
  end

  def create
    @url = UserUrl.new(url_params)
    @url.short_url = @url.make_short_url

    if @url.save
      redirect_to user_urls_path, notice: "Url Created!"
    else
      render :new
    end
  end

  def new
    @url = UserUrl.new
  end

  private

  def url_params
    params.require(:user_url).permit(:long_url, :short_url, :id)
  end

  def log_ip_address
    ip = request.remote_ip
    @url.url_statistics.create(visit_ip_address: ip)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrlMaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/url_statistics/index.html.erb
<%= link_to "View All URLs", user_urls_path %>

<h2>Showing Statistics for <%= @url.short_url %></h2>

<p>Long Url: <%= @url.long_url %></p>
<p>Short Url: <%= @url.short_url %></p>

<div>
  <p>IP Addresses Accessing This URL:</p>
  <table>
    <tr>
      <th>Ip Address</th>
      <th>Time Accessed</th>
    </tr>
  
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.visit_ip_address %></td>
        <td><%= statistic.created_at.strftime("%B %d, %Y") %></td>
      </tr>
    <% end %>
    
  </table>
</div>

app/views/user_urls/index.html.erb
<h1>All Urls</h1>

<%= link_to "Click to Create A New Tiny URL!", new_user_url_path %>

</br>
</br>

<table>
  <tr>
    <th>Url</th>
    <th>Actions</th>
  </tr>
  <% @urls.each do |url| %>
    <tr>
      <td><%= link_to url.short_url, user_url_path(url) %></td>
      <td><%= link_to "View Url Statistics", user_url_url_statistics_path(url) %></td>
    </tr>
  <% end %>
</table>

app/views/user_urls/new.html.erb
<h1>Create A New Url</h1>

<% if @url.errors.any? %>
  <% @url.errors.full_messages.each do |message|%>
     <p><%= message %> </p>
  <%end%>
<%end%>

</br>

<%= form_for @url do |form| %>
  <p>Please input a url you want to shorten.  Follow the pattern of: "https://my_url"
  <p><%= form.text_field :long_url %></p>
  <%= form.submit %>
<% end %>